name: CI/CD Pipeline

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up JDK 11
      uses: actions/setup-java@v2
      with:
        java-version: '11'
        distribution: 'adopt'

    - name: Download and extract JavaFX SDK
      run: |
        if [ ! -d ~/javafx-sdk ]; then
          mkdir -p ~/javafx-sdk
          wget -q https://download2.gluonhq.com/openjfx/${JAVAFX_VERSION}/openjfx-${JAVAFX_VERSION}_sdk-linux-x64_bin.tar.gz -O javafx-sdk.tar.gz
          tar -xzf javafx-sdk.tar.gz -C ~/javafx-sdk --strip-components=1
        fi
      env:
        JAVAFX_VERSION: 17.0.1

    - name: Compile Java files
      run: |
        export PATH_TO_FX=~/javafx-sdk/lib
        find . -name "*.java" > sources.txt
        javac --module-path $PATH_TO_FX --add-modules javafx.controls,javafx.fxml -encoding UTF-8 -d out @sources.txt

    - name: Create JAR file
      run: |
        cd out
        echo "Main-Class: fr.majestycraft.Main" > manifest.txt
        jar cvfm MajestyCraft.jar manifest.txt *