name: CI/CD Pipeline

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up JDK 11
      uses: actions/setup-java@v2
      with:
        java-version: '11'
        distribution: 'adopt'
        
    - name: Install JavaFX
      run: |
        JAVAFX_VERSION=17.0.1
        if [ ! -d ~/javafx-sdk ]; then
          mkdir -p ~/javafx-sdk
          wget -q https://download2.gluonhq.com/openjfx/${JAVAFX_VERSION}/openjfx-${JAVAFX_VERSION}_sdk-linux-x64_bin.tar.gz -O javafx-sdk.tar.gz
          tar -xzf javafx-sdk.tar.gz -C ~/javafx-sdk --strip-components=1
        fi