name: CI/CD Pipeline

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up JDK 11
      uses: actions/setup-java@v2
      with:
        java-version: '11'
        distribution: 'adopt'

    - name: Cache JavaFX
      uses: actions/cache@v2
      with:
        path: ~/javafx-sdk
        key: ${{ runner.os }}-javafx-${{ env.JAVAFX_VERSION }}

    - name: Download JavaFX
      run: |
        if [ ! -d ~/javafx-sdk ]; then
          mkdir -p ~/javafx-sdk
          wget -q https://gluonhq.com/download/javafx-${{ env.JAVAFX_VERSION }}-sdk-linux -O javafx-sdk.zip
          unzip -q javafx-sdk.zip -d ~/javafx-sdk
        fi

    - name: Build and test with Maven
      run: |
        export PATH_TO_FX=~/javafx-sdk/lib
        mvn --batch-mode --update-snapshots -Djavafx.platform=linux -Dprism.order=sw clean verify