name: CI/CD Pipeline

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up JDK 11
      uses: actions/setup-java@v2
      with:
        java-version: '11'
        distribution: 'adopt'

    - name: Install JavaFX dependencies with Maven
      run: |
        mvn -B dependency:get -DgroupId=org.openjfx -DartifactId=javafx-sdk -Dversion=${JAVAFX_VERSION} -Dclassifier=linux-x64_bin -Dtransitive=false -Ddest=.
        mkdir -p ~/javafx-sdk
        tar -xzf javafx-sdk-${JAVAFX_VERSION}-linux-x64_bin.tar.gz -C ~/javafx-sdk --strip-components=1
      env:
        JAVAFX_VERSION: 17.0.1