name: CI/CD Pipeline

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up JDK 11
      uses: actions/setup-java@v2
      with:
        java-version: '11'
        distribution: 'adopt'

    - name: Compile Java files
      run: |
        export PATH_TO_FX=~/javafx-sdk/lib
        find . -name "*.java" > sources.txt
        javac --module-path $PATH_TO_FX --add-modules javafx.controls,javafx.fxml -d out @sources.txt

    - name: Create JAR file
      run: |
        cd out
        echo "Main-Class: fr.majestycraft.Main" > manifest.txt
        jar cvfm MajestyCraft.jar manifest.txt *