name: CI/CD Pipeline

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up JDK 11
      uses: actions/setup-java@v2
      with:
        java-version: '11'
        distribution: 'adopt'
        
    - name: Download and extract JavaFX SDK
      run: |
        mkdir -p ~/javafx-sdk
        wget -q https://download2.gluonhq.com/openjfx/17.0.6/openjfx-17.0.6_linux-aarch64_bin-sdk.zip -O javafx-sdk.zip
        unzip -q javafx-sdk.zip -d ~/javafx-sdk

    - name: Set up environment variables
      run: |
        echo "PATH_TO_FX=~/javafx-sdk/lib" >> $GITHUB_ENV
        